var mongoose = require("mongoose");

var standardItems = [
{Name:"Arrows", Type:"Ammunition", Amount:20,	Cost:1,	Weight:1},
{Name:"Blowgun Needles", Type:"Ammunition", Amount:50,	Cost:1,	Weight:1},
{Name:"Crossbow bolts",Type:"Ammunition", Amount:20,	Cost:1,	Weight:1.5},
{Name:"Sling Bullets", Type:"Ammunition", Amount:20,	Cost:0.04, Weight:	1.5},	
{Name:"Crystal", Type:"Arcane Focus",	Cost:10, Weight:1},
{Name:"Orb", Type:"Arcane Focus",	Cost:20,	Weight:3},
{Name:"Rod", Type:"Arcane Focus",	Cost:10,	Weight:2},
{Name:"Staff", Type:"Arcane Focus",	Cost:5,	Weight:4},
{Name:"Wand", Type:"Arcane Focus",	Cost:10,	Weight:1},	
{Name:"Sprig of Mistletoe", Type: "Druidic Focus",	Cost:1,	Weight:0},
{Name:"Totem",	Type: "Druidic Focus", Cost:1,	Weight:0},
{Name:"Wooden Staff", Type: "Druidic Focus", Cost:5,	Weight:4},
{Name:"Yew Wand", Type: "Druidic Focus", Cost:10,	Weight:1},	
{Name: "Amulet", Type: "Holy Symbols",	Cost:5,	Weight:1},
{Name: "Emblem", Type: "Holy Symbols",	Cost:5,	Weight:0},
{Name: "Reliquary", Type: "Holy Symbols",	Cost:5,	Weight:2},	
{Name: "Backpack", Type: "Containers",	Cost:2,	Weight:5},
{Name: "Barrel", Type: "Containers",	Cost:2,	Weight:70},
{Name: "Basket", Type: "Containers",	Cost:0.40,	Weight:2},
{Name: "Bucket", Type: "Containers",	Cost:0.05, 	Weight:2},
{Name: "Case-Crossbow Bolt", Type: "Containers",	Cost:1,	Weight:1},
{Name: "Case-Map/Scroll", Type: "Containers", Cost:1,	Weight:1},
{Name: "Chest", Type: "Containers",	Cost:5,	Weight:25},
{Name: "Flask or Tankard", Type: "Containers",	Cost:0.02, 	Weight:1},
{Name: "Glass Bottle", Type: "Containers",	Cost:25,	Weight:2},
{Name: "Jug or Pitcher", Type: "Containers",	Cost:0.02, 	Weight:4},
{Name: "Pouch", Type: "Containers",	Cost:0.50,	Weight:1},
{Name: "Quiver", Type: "Containers",	Cost:1,	Weight:1},
{Name: "Sack", Type: "Containers",	Cost:0.01, 	Weight:0.5},
{Name: "Vial", Type: "Containers",	Cost:1,	Weight:0},
{Name: "Waterskin", Type: "Containers",	Cost:0.20,	Weight:5},
{Name:"Acid (vial)", Type: "Usable Items",	Cost:25,	Weight:1},
{Name:"Alchemis's Fire(flask)", Type: "Usable Items",	Cost:50,	Weight:1},
{Name:"Antitoxin (vial)", Type: "Usable Items",	Cost:50, 	Weight:0},
{Name:"Ball Bearings(bag of 1,00)", Type: "Usable Items",	Cost:1,	Weight:2},
{Name:"Caltrops(bag of 20)", Type: "Usable Items",	Cost:1,	Weight:2},
{Name:"Holy Water(flask)", Type: "Usable Items",	Cost:25,	Weight:1},
{Name:"Oil (flask)", Type: "Usable Items",	Cost:0.10,	Weight:1},
{Name:"Poison, basic(vial)", Type: "Usable Items",	Cost:100,	Weight:0},
{Name:"Potion of Healing", Type: "Usable Items",	Cost:50,	Weight:0.5},
{Name: "Climber's Kit", Type: "Kits",	Cost:25,	Weight:12},
{Name: "Disguise Kit", Type: "Kits",	Cost:25,	Weight:3},
{Name: "Forgery Kit", Type: "Kits",	Cost:15,	Weight:5},
{Name: "Herbalism Kit", Type: "Kits",	Cost:5,	Weight:3},
{Name: "Healer's Kit", Type: "Kits",	Cost:25,	Weight:3},
{Name: "Mess Kit", Type: "Kits", Cost:0.20,	Weight:1},
{Name: "Poisoner's Kit", Type: "Kits",	Cost:50,	Weight:2},
{Name:"Common Clotes", Type:"Clothes",	Cost:0.50,	Weight:3},
{Name:"Costume", Type:"Clothes",	Cost:5,	Weight:4},
{Name:"Fine Clothes", Type:"Clothes",	Cost:15,	Weight:6},
{Name:"Robes", Type:"Clothes",	Cost:1,	Weight:4},
{Name:"Traveler's Clothes", Type:"Clothes",	Cost:2,	Weight:4},
{Name:"Abacus", Type:"Common Item",	Cost:2,	Weight:2},
{Name:"Bedroll", Type:"Common Item",	Cost:1,	Weight:2},
{Name:"Bell", Type:"Common Item",	Cost:1,	Weight:0},
{Name:"Blanket", Type:"Common Item",	Cost:0.50,	Weight:5},
{Name:"Block and Tackle", Type:"Common Item",	Cost:1,	Weight:5},
{Name:"Book", Type:"Common Item",	Cost:25,	Weight:5},
{Name:"Candle", Type:"Common Item",	Cost:0.01, 	Weight:0},
{Name:"Chain (10 ft)", Type:"Common Item",	Cost:5,	Weight:10},
{Name:"Chalk", Type:"Common Item",	Cost:0.01, 	Weight:0},
{Name:"Component's Pouch", Type:"Common Item",	Cost:25,	Weight:2},
{Name:"Crowbar", Type:"Common Item",	Cost:2,	Weight:5},
{Name:"Fishing Tackle", Type:"Common Item",	Cost:1,	Weight:4},
{Name:"Grappling Hook", Type:"Common Item",	Cost:2,	Weight:4},
{Name:"Hammer", Type:"Common Item",	Cost:1,	Weight:3},
{Name:"Hourglass", Type:"Common Item",	Cost:25,	Weight:1},
{Name:"Hunting Trap", Type:"Common Item",	Cost:5,	Weight:25},
{Name:"Ink", Type:"Common Item",    Cost:10,	Weight:0},
{Name:"Ink Pen", Type:"Common Item",	Cost:0.02, 	Weight:0},
{Name:"Ladder (10 ft)", Type:"Common Item",	Cost:0.10,	Weight:25},
{Name:"Lamp", Type:"Common Item", Cost:0.50,	Weight:1},
{Name:"Lantern - Bullseye", Type:"Common Item",	Cost:10,	Weight:2},
{Name:"Lantern - Hodded", Type:"Common Item",	Cost:5,	Weight:2},
{Name:"Lock", Type:"Common Item",	Cost:10,	Weight:1},
{Name:"Magnifying Glass", Type:"Common Item",	Cost:100,	Weight:0},
{Name:"Manacles", Type:"Common Item",	Cost:2,	Weight:6},
{Name:"Miner's Pick", Type:"Common Item",	Cost:2,	Weight:10},
{Name:"Paper", Type:"Common Item", 	Cost:0.20,	Weight:0},
{Name:"Parchment", Type:"Common Item",	Cost:0.10,	Weight:0},
{Name:"Perfume (vial)", Type:"Common Item",	Cost:5,	Weight:0},
{Name:"Piton", Type:"Common Item",	Cost:0.05, 	Weight:0.25},
{Name:"Pole(10 ft)", Type:"Common Item",	Cost:0.05, 	Weight:7},
{Name:"Pot - Iron", Type:"Common Item",	Cost:2,	Weight:10},
{Name:"Portable Ram", Type:"Common Item",	Cost:4,	Weight:35},
{Name:"Rations", Type:"Common Item", Amount:1,	Cost:0.50,	Weight:2},
{Name:"Rope - Hemp (50 ft)", Type:"Common Item",	Cost:1,	Weight:10},
{Name:"Rope - Silk (50 ft)", Type:"Common Item",	Cost:10,	Weight:5},
{Name:"Scale - Merchants", Type:"Common Item",	Cost:5,	Weight:3},
{Name:"Sealing Wax", Type:"Common Item",	Cost:0.50,	Weight:0},
{Name:"Shovel", Type:"Common Item",	Cost:2,	Weight:5},
{Name:"Signal Whisle", Type:"Common Item",	Cost:0.05, 	Weight:0},
{Name:"Signet Ring", Type:"Common Item",	Cost:5,	Weight:0},
{Name:"Sledgehammer", Type:"Common Item",	Cost:2,	Weight:10},
{Name:"Spellbook", Type:"Common Item",	Cost:50,	Weight:3},
{Name:"Spikes - Iron", Type:"Common Item", Amount:10,	Cost:1,	Weight:5},
{Name:"Spyglass", Type:"Common Item",	Cost:1000,	Weight:1},
{Name:"Tent - 2 person", Type:"Common Item",	Cost:2,	Weight:20}, 
{Name:"Tinderbox", Type:"Common Item",	Cost:0.50,	Weight:1},
{Name:"Torch",	Type:"Common Item", Cost:0.01, 	Weight:1},
{Name:"Whetstone",	Type:"Common Item", Cost:0.01, 	Weight:1}]

module.exports = standardItems;