var mongoose = require("mongoose");

var standardItems = [
{Name:"Arrows", Type:"Ammunition", Amount:20,	Cost:100,	Weight:100},
{Name:"Blowgun Needles", Type:"Ammunition", Amount:5000,	Cost:1,	Weight:100},
{Name:"Crossbow bolts",Type:"Ammunition", Amount:2000,	Cost:1,	Weight:150},
{Name:"Sling Bullets", Type:"Ammunition", Amount:2000,	Cost:0.04, Weight:	150},	
{Name:"Crystal", Type:"Arcane Focus",	Cost:1000, Weight:100},
{Name:"Orb", Type:"Arcane Focus",	Cost:2000,	Weight:300},
{Name:"Rod", Type:"Arcane Focus",	Cost:1000,	Weight:200},
{Name:"Staff", Type:"Arcane Focus",	Cost:500,	Weight:400},
{Name:"Wand", Type:"Arcane Focus",	Cost:1000,	Weight:100},	
{Name:"Sprig of Mistletoe", Type: "Druidic Focus",	Cost:100,	Weight:0},
{Name:"Totem",	Type: "Druidic Focus", Cost:100,	Weight:0},
{Name:"Wooden Staff", Type: "Druidic Focus", Cost:500,	Weight:400},
{Name:"Yew Wand", Type: "Druidic Focus", Cost:1000,	Weight:100},	
{Name: "Amulet", Type: "Holy Symbols",	Cost:500,	Weight:100},
{Name: "Emblem", Type: "Holy Symbols",	Cost:500,	Weight:0},
{Name: "Reliquary", Type: "Holy Symbols",	Cost:500,	Weight:200},	
{Name: "Backpack", Type: "Containers",	Cost:200,	Weight:500},
{Name: "Barrel", Type: "Containers",	Cost:200,	Weight:7000},
{Name: "Basket", Type: "Containers",	Cost:40,	Weight:200},
{Name: "Bucket", Type: "Containers",	Cost:5, 	Weight:200},
{Name: "Case-Crossbow Bolt", Type: "Containers",	Cost:100,	Weight:100},
{Name: "Case-Map/Scroll", Type: "Containers", Cost:100,	Weight:100},
{Name: "Chest", Type: "Containers",	Cost:500,	Weight:2500},
{Name: "Flask or Tankard", Type: "Containers",	Cost:2, 	Weight:100},
{Name: "Glass Bottle", Type: "Containers",	Cost:2500,	Weight:200},
{Name: "Jug or Pitcher", Type: "Containers",	Cost:2, 	Weight:400},
{Name: "Pouch", Type: "Containers",	Cost:50,	Weight:100},
{Name: "Quiver", Type: "Containers",	Cost:100,	Weight:100},
{Name: "Sack", Type: "Containers",	Cost:1, 	Weight:50},
{Name: "Vial", Type: "Containers",	Cost:100,	Weight:0},
{Name: "Waterskin", Type: "Containers",	Cost:20,	Weight:500},
{Name:"Acid (vial)", Type: "Usable Items",	Cost:2500,	Weight:100},
{Name:"Alchemis's Fire(flask)", Type: "Usable Items",	Cost:5000,	Weight:100},
{Name:"Antitoxin (vial)", Type: "Usable Items",	Cost:5000, 	Weight:0},
{Name:"Ball Bearings(bag of 1,00)", Type: "Usable Items",	Cost:100,	Weight:200},
{Name:"Caltrops(bag of 20)", Type: "Usable Items",	Cost:100,	Weight:200},
{Name:"Holy Water(flask)", Type: "Usable Items",	Cost:2500,	Weight:100},
{Name:"Oil (flask)", Type: "Usable Items",	Cost:10,	Weight:100},
{Name:"Poison, basic(vial)", Type: "Usable Items",	Cost:10000,	Weight:0},
{Name:"Potion of Healing", Type: "Usable Items",	Cost:5000,	Weight:50},
{Name: "Climber's Kit", Type: "Kits",	Cost:2500,	Weight:1200},
{Name: "Disguise Kit", Type: "Kits",	Cost:2500,	Weight:300},
{Name: "Forgery Kit", Type: "Kits",	Cost:1500,	Weight:500},
{Name: "Herbalism Kit", Type: "Kits",	Cost:500,	Weight:300},
{Name: "Healer's Kit", Type: "Kits",	Cost:2500,	Weight:300},
{Name: "Mess Kit", Type: "Kits", Cost:20,	Weight:100},
{Name: "Poisoner's Kit", Type: "Kits",	Cost:5000,	Weight:200},
{Name:"Common Clotes", Type:"Clothes",	Cost:50,	Weight:300},
{Name:"Costume", Type:"Clothes",	Cost:500,	Weight:400},
{Name:"Fine Clothes", Type:"Clothes",	Cost:1500,	Weight:600},
{Name:"Robes", Type:"Clothes",	Cost:100,	Weight:400},
{Name:"Traveler's Clothes", Type:"Clothes",	Cost:200,	Weight:400},
{Name:"Abacus", Type:"Common Item",	Cost:200,	Weight:200},
{Name:"Bedroll", Type:"Common Item",	Cost:100,	Weight:200},
{Name:"Bell", Type:"Common Item",	Cost:100,	Weight:0},
{Name:"Blanket", Type:"Common Item",	Cost:50,	Weight:500},
{Name:"Block and Tackle", Type:"Common Item",	Cost:100,	Weight:500},
{Name:"Book", Type:"Common Item",	Cost:2500,	Weight:500},
{Name:"Candle", Type:"Common Item",	Cost:1, 	Weight:0},
{Name:"Chain (10 ft)", Type:"Common Item",	Cost:500,	Weight:1000},
{Name:"Chalk", Type:"Common Item",	Cost:1, 	Weight:0},
{Name:"Component's Pouch", Type:"Common Item",	Cost:2500,	Weight:200},
{Name:"Crowbar", Type:"Common Item",	Cost:200,	Weight:500},
{Name:"Fishing Tackle", Type:"Common Item",	Cost:100,	Weight:400},
{Name:"Grappling Hook", Type:"Common Item",	Cost:200,	Weight:400},
{Name:"Hammer", Type:"Common Item",	Cost:100,	Weight:300},
{Name:"Hourglass", Type:"Common Item",	Cost:2500,	Weight:100},
{Name:"Hunting Trap", Type:"Common Item",	Cost:500,	Weight:2500},
{Name:"Ink", Type:"Common Item",    Cost:1000,	Weight:0},
{Name:"Ink Pen", Type:"Common Item",	Cost:200, 	Weight:0},
{Name:"Ladder (10 ft)", Type:"Common Item",	Cost:10,	Weight:2500},
{Name:"Lamp", Type:"Common Item", Cost:50,	Weight:100},
{Name:"Lantern - Bullseye", Type:"Common Item",	Cost:1000,	Weight:200},
{Name:"Lantern - Hodded", Type:"Common Item",	Cost:500,	Weight:200},
{Name:"Lock", Type:"Common Item",	Cost:1000,	Weight:100},
{Name:"Magnifying Glass", Type:"Common Item",	Cost:10000,	Weight:0},
{Name:"Manacles", Type:"Common Item",	Cost:200,	Weight:600},
{Name:"Miner's Pick", Type:"Common Item",	Cost:200,	Weight:1000},
{Name:"Paper", Type:"Common Item", 	Cost:20,	Weight:0},
{Name:"Parchment", Type:"Common Item",	Cost:10,	Weight:0},
{Name:"Perfume (vial)", Type:"Common Item",	Cost:500,	Weight:0},
{Name:"Piton", Type:"Common Item",	Cost:5, 	Weight:25},
{Name:"Pole(10 ft)", Type:"Common Item",	Cost:5, 	Weight:700},
{Name:"Pot - Iron", Type:"Common Item",	Cost:200,	Weight:1000},
{Name:"Portable Ram", Type:"Common Item",	Cost:400,	Weight:3500},
{Name:"Rations", Type:"Common Item", Amount:1,	Cost:50,	Weight:200},
{Name:"Rope - Hemp (50 ft)", Type:"Common Item",	Cost:100,	Weight:1000},
{Name:"Rope - Silk (50 ft)", Type:"Common Item",	Cost:1000,	Weight:500},
{Name:"Scale - Merchants", Type:"Common Item",	Cost:500,	Weight:300},
{Name:"Sealing Wax", Type:"Common Item",	Cost:50,	Weight:000},
{Name:"Shovel", Type:"Common Item",	Cost:200,	Weight:500},
{Name:"Signal Whisle", Type:"Common Item",	Cost:5, 	Weight:000},
{Name:"Signet Ring", Type:"Common Item",	Cost:500,	Weight:000},
{Name:"Sledgehammer", Type:"Common Item",	Cost:200,	Weight:1000},
{Name:"Spellbook", Type:"Common Item",	Cost:5000,	Weight:300},
{Name:"Spikes - Iron", Type:"Common Item", Amount:1000,	Cost:1,	Weight:500},
{Name:"Spyglass", Type:"Common Item",	Cost:100000,	Weight:100},
{Name:"Tent - 2 person", Type:"Common Item",	Cost:200,	Weight:2000}, 
{Name:"Tinderbox", Type:"Common Item",	Cost:50,	Weight:100},
{Name:"Torch",	Type:"Common Item", Cost:1, 	Weight:100},
{Name:"Whetstone",	Type:"Common Item", Cost:1, 	Weight:100}]

module.exports = standardItems;