var mongoose = require("mongoose")

var standardWeapons =
[
    {Name: "Club",
    Type:"Simple",
    Cost: 1,
    Damage: {Die:"1D4", Type: "Bludgeoning"},
    Weight: 200,
    Properties: {Light:true}
    },   
    {Name: "Dagger",
    Type:"Simple",
    Cost: 200,
    Damage: {Die:"1D4", Type: "Piercing"},
    Weight: 100,
    Properties: {Finess:true,Light:true, Range: "20/60",Thrown:true}
    },   
    {Name: "Great-Club",
    Type:"Simple",
    Cost: 20,
    Damage: {Die:"1D8", Type: "Bludgeoning"},
    Weight: 1000,
    Properties: {TwoHanded:true}
    },   
    {Name: "Hand-Axe",
    Type:"Simple",
    Cost: 500,
    Damage: {Die:"1D6", Type: "Slashing"},
    Weight: 200,
    Properties: {Light:true, Range: "20/60", Thrown:true}
    },
    {Name: "Javelin",
    Type:"Simple",
    Cost: 50,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight: 200,
    Properties: {Thrown:true, Range:"30/120"},
    },
    {Name: "Light Hammer",
    Type:"Simple",
    Cost: 200,
    Damage: {Die:"1D4", Type: "Bludgeoning"},
    Weight: 200,
    Properties: {Light:true, Range: "20/60", Thrown:true}
    },   
    {Name: "Mace",
    Type:"Simple",
    Cost: 500,
    Damage: {Die:"1D6", Type: "Bludgeoning"},
    Weight: 400,
    Properties: {}
    },   
    {Name: "Quarterstaff",
    Type:"Simple",
    Cost: 20,
    Damage: {Die:"1D6", Type: "Bludgeoning"},
    Weight: 400,
    Properties: {Versatile:"1D8"}
    },
    {Name: "Sickle",
    Type:"Simple",
    Cost: 100,
    Damage: {Die:"1D4", Type: "Slashing"},
    Weight: 200,
    Properties: {Light:true}
    },
    {Name: "Spear",
    Type:"Simple",
    Cost: 100,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight: 300,
    Properties: {Thrown:true, Range:"20/60", Versatile:"1D8"}
    },   
    {Name: "Unarmed",
    Type:"Simple",
    Cost: 0,
    Damage: {Die:"1D1", Type: "Bludgeoning"},
    Weight: 0,
    Properties: {}
    },
    {Name: "Crossbow-light",
    Type:"Simple-Ranged",
    Cost: 2500,
    Damage: {Die:"1D8", Type: "Piercing"},
    Weight: 500,
    Properties: {Ammunition:true, Range:"80/320", Loading:true, TwoHanded:true}
    },   
    {Name: "Dart",
    Type:"Simple-Ranged",
    Cost: 5,
    Damage: {Die:"1D4", Type: "Piercing"},
    Weight: 25,
    Properties: {Finesse:true, Range:"20/60", Thrown:true}
    },   
    {Name: "Shortbow",
    Type:"Simple-Ranged",
    Cost: 2500,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight: 200,
    Properties: {Ammunition:true, Range:"80/320", TwoHanded:true}
    },   
    {Name: "Sling",
    Type:"Simple-Ranged",
    Cost: 10,
    Damage: {Die:"1D4", Type: "Piercing"},
    Weight: 0,
    Properties: {Ammunition:true, Range:"30/120"}
    },   
    {Name: "Battleaxe",
    Type:"Martial",
    Cost: 1000,
    Damage: {Die:"1D8", Type: "Slashing"},
    Weight: 400,
    Properties: {Versatile:"1D10"}
    },   
    {Name: "Flail",
    Type:"Martial",
    Cost: 1000,
    Damage: {Die:"1D8", Type: "Bludgeoning"},
    Weight: 200,
    Properties: {}
    },   
    {Name: "Glaive",
    Type:"Martial",
    Cost: 2000,
    Damage: {Die:"1D10", Type: "Slashing"},
    Weight:600,
    Properties: {Heavy:true, Reach:true, TwoHanded:true}
    },   
    {Name: "Greataxe",
    Type:"Martial",
    Cost: 3000,
    Damage: {Die:"1D12", Type: "Slashing"},
    Weight:700,
    Properties: {Heavy:true, TwoHanded:true}
    },   
    {Name: "Great-sword",
    Type:"Martial",
    Cost: 5000,
    Damage: {Die:"2D6", Type: "Slashing"},
    Weight:600,
    Properties: {Heavy:true, TwoHanded:true}
    },    
    {Name: "Halberd",
    Type:"Martial",
    Cost: 2000,
    Damage: {Die:"1D10", Type: "Slashing"},
    Weight:600,
    Properties: {Heavy:true, Reach:true, TwoHanded:true}
    },    
    {Name: "Lance",
    Type:"Martial",
    Cost: 1000,
    Damage: {Die:"1D12", Type: "Piercing"},
    Weight:600,
    Properties: {Special:true, Reach:true}
    },   
    {Name: "Long-sword",
    Type:"Martial",
    Cost: 1500,
    Damage: {Die:"1D8", Type: "Slashing"},
    Weight:300,
    Properties: {Versatile:"1D10"}
    },   
    {Name: "Maul",
    Type:"Martial",
    Cost: 1000,
    Damage: {Die:"2D6", Type: "Bludgeoning"},
    Weight:1000,
    Properties: {Heavy:true, TwoHanded:true}
    },   
    {Name: "Morning-star",
    Type:"Martial",
    Cost: 1500,
    Damage: {Die:"1D8", Type: "Piercing"},
    Weight:400,
    Properties: {}
    },   
    {Name: "Pike",
    Type:"Martial",
    Cost: 500,
    Damage: {Die:"1D10", Type: "Piercing"},
    Weight:1800,
    Properties: {Heavy:true, Reach:true, TwoHanded:true}
    },   
    {Name: "Rapier",
    Type:"Martial",
    Cost: 2500,
    Damage: {Die:"1D8", Type: "Piercing"},
    Weight:200,
    Properties: {Finess:true}
    },   
    {Name: "Scimitar",
    Type:"Martial",
    Cost: 2500,
    Damage: {Die:"1D6", Type: "Slashing"},
    Weight:300,
    Properties: {Finesse:true, Light:true}
    },   
    {Name: "Short-sword",
    Type:"Martial",
    Cost: 1000,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight:200,
    Properties: {Finesse:true, Light:true}
    },   
    {Name: "Trident",
    Type:"Martial",
    Cost: 500,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight:400,
    Properties: {Range: "20/60", Thrown:true, Versatile:"1D8"}
    },   
    {Name: "War Pick",
    Type:"Martial",
    Cost: 500,
    Damage: {Die:"1D8", Type: "Piercing"},
    Weight:200,
    Properties: {}
    },   
    {Name: "War-hammer",
    Type:"Martial",
    Cost: 1500,
    Damage: {Die:"1D8", Type: "Bludgeoning"},
    Weight:200,
    Properties: {Versatile: "1D10"}
    },   
    {Name: "Whip",
    Type:"Martial",
    Cost: 200,
    Damage: {Die:"1D4", Type: "Slashing"},
    Weight:300,
    Properties: {Finesse:true, Reach:true}
    },   
    {Name: "Blowgun",
    Type:"Martial-Ranged",
    Cost: 1000,
    Damage: {Die:"1D1", Type: "Piercing"},
    Weight:100,
    Properties: {Ammunition:true, Range: "25/100", Loading:true}
    },   
    {Name: "Crossbow-hand",
    Type:"Martial-Ranged",
    Cost: 7500,
    Damage: {Die:"1D6", Type: "Piercing"},
    Weight:300,
    Properties: {Ammunition:true, Range: "30/120", Light:true, Loading:true}
    },   
    {Name: "Crossbow-Heavy",
    Type:"Martial-Ranged",
    Cost: 5000,
    Damage: {Die:"1D10", Type: "Piercing"},
    Weight:1800,
    Properties: {Ammunition:true, Range: "100/400", Heavy:true, TwoHanded:true, Loading:true}
    },   
    {Name: "Longbow",
    Type:"Martial-Ranged",
    Cost: 5000,
    Damage: {Die:"1D8", Type: "Piercing"},
    Weight:200,
    Properties: {Ammunition:true, Range: "150/600", Heavy:true, TwoHanded:true}
    },   
    {Name: "Net",
    Type:"Martial-Ranged",
    Cost: 100,
    Damage: {Die:"", Type: ""},
    Weight:300,
    Properties: {Special:true, Range: "5/15"}
    }           
]


module.exports = standardWeapons;
